modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="hidetab"
version="02"
displayName="HIDE-TAB"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="zaibalbliat_777"
description="Мод скрывает список игроков (Tab) и отключает автодополнение ников в чате."

[[dependencies.hidetab]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




